# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: my.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x08my.proto\"7\n\x0e\x42uzzwordConfig\x12%\n\x08keywords\x18\x01 \x03('
    b'\x0b\x32\x13.BuzzwordShowConfig\"x\n\x12\x42uzzwordShowConfig\x12\x0c\n\x04name\x18\x01 \x01('
    b'\t\x12\x0e\n\x06schema\x18\x02 \x01(\t\x12\x0e\n\x06source\x18\x03 \x01(\x05\x12\n\n\x02id\x18\x04 \x01('
    b'\x03\x12\x13\n\x0b\x62uzzword_id\x18\x05 \x01(\x03\x12\x13\n\x0bschema_type\x18\x06 \x01('
    b'\x05\"\xa1\x01\n\tCommandDm\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0b\n\x03oid\x18\x02 \x01('
    b'\x03\x12\x0b\n\x03mid\x18\x03 \x01(\t\x12\x0f\n\x07\x63ommand\x18\x04 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x05 '
    b'\x01(\t\x12\x10\n\x08progress\x18\x06 \x01(\x05\x12\r\n\x05\x63time\x18\x07 \x01(\t\x12\r\n\x05mtime\x18\x08 '
    b'\x01(\t\x12\r\n\x05\x65xtra\x18\t \x01(\t\x12\r\n\x05idStr\x18\n \x01('
    b'\t\"/\n\rDanmakuAIFlag\x12\x1e\n\x08\x64m_flags\x18\x01 \x03('
    b'\x0b\x32\x0c.DanmakuFlag\"\xd6\x01\n\x0b\x44\x61nmakuElem\x12\n\n\x02id\x18\x01 \x01('
    b'\x03\x12\x10\n\x08progress\x18\x02 \x01(\x05\x12\x0c\n\x04mode\x18\x03 \x01('
    b'\x05\x12\x10\n\x08\x66ontsize\x18\x04 \x01(\x05\x12\r\n\x05\x63olor\x18\x05 \x01('
    b'\r\x12\x0f\n\x07midHash\x18\x06 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x07 \x01(\t\x12\r\n\x05\x63time\x18\x08 '
    b'\x01(\x03\x12\x0e\n\x06weight\x18\t \x01(\x05\x12\x0e\n\x06\x61\x63tion\x18\n \x01(\t\x12\x0c\n\x04pool\x18\x0b '
    b'\x01(\x05\x12\r\n\x05idStr\x18\x0c \x01(\t\x12\x0c\n\x04\x61ttr\x18\r \x01('
    b'\x05\")\n\x0b\x44\x61nmakuFlag\x12\x0c\n\x04\x64mid\x18\x01 \x01(\x03\x12\x0c\n\x04\x66lag\x18\x02 \x01('
    b'\r\"K\n\x11\x44\x61nmakuFlagConfig\x12\x10\n\x08rec_flag\x18\x01 \x01(\x05\x12\x10\n\x08rec_text\x18\x02 \x01('
    b'\t\x12\x12\n\nrec_switch\x18\x03 \x01('
    b'\x05\"\xcc\x04\n\x18\x44\x61nmuDefaultPlayerConfig\x12)\n!player_danmaku_use_default_config\x18\x01 \x01('
    b'\x08\x12,\n$player_danmaku_ai_recommended_switch\x18\x04 \x01('
    b'\x08\x12+\n#player_danmaku_ai_recommended_level\x18\x05 \x01(\x05\x12\x1f\n\x17player_danmaku_blocktop\x18\x06 '
    b'\x01(\x08\x12\"\n\x1aplayer_danmaku_blockscroll\x18\x07 \x01(\x08\x12\"\n\x1aplayer_danmaku_blockbottom\x18\x08 '
    b'\x01(\x08\x12$\n\x1cplayer_danmaku_blockcolorful\x18\t \x01(\x08\x12\"\n\x1aplayer_danmaku_blockrepeat\x18\n '
    b'\x01(\x08\x12#\n\x1bplayer_danmaku_blockspecial\x18\x0b \x01(\x08\x12\x1e\n\x16player_danmaku_opacity\x18\x0c '
    b'\x01(\x02\x12$\n\x1cplayer_danmaku_scalingfactor\x18\r \x01(\x02\x12\x1d\n\x15player_danmaku_domain\x18\x0e '
    b'\x01(\x02\x12\x1c\n\x14player_danmaku_speed\x18\x0f \x01(\x05\x12$\n\x1cinline_player_danmaku_switch\x18\x10 '
    b'\x01(\x08\x12)\n!player_danmaku_senior_mode_switch\x18\x11 \x01('
    b'\x05\"\xfe\x05\n\x11\x44\x61nmuPlayerConfig\x12\x1d\n\x15player_danmaku_switch\x18\x01 \x01('
    b'\x08\x12\"\n\x1aplayer_danmaku_switch_save\x18\x02 \x01(\x08\x12)\n!player_danmaku_use_default_config\x18\x03 '
    b'\x01(\x08\x12,\n$player_danmaku_ai_recommended_switch\x18\x04 \x01('
    b'\x08\x12+\n#player_danmaku_ai_recommended_level\x18\x05 \x01(\x05\x12\x1f\n\x17player_danmaku_blocktop\x18\x06 '
    b'\x01(\x08\x12\"\n\x1aplayer_danmaku_blockscroll\x18\x07 \x01(\x08\x12\"\n\x1aplayer_danmaku_blockbottom\x18\x08 '
    b'\x01(\x08\x12$\n\x1cplayer_danmaku_blockcolorful\x18\t \x01(\x08\x12\"\n\x1aplayer_danmaku_blockrepeat\x18\n '
    b'\x01(\x08\x12#\n\x1bplayer_danmaku_blockspecial\x18\x0b \x01(\x08\x12\x1e\n\x16player_danmaku_opacity\x18\x0c '
    b'\x01(\x02\x12$\n\x1cplayer_danmaku_scalingfactor\x18\r \x01(\x02\x12\x1d\n\x15player_danmaku_domain\x18\x0e '
    b'\x01(\x02\x12\x1c\n\x14player_danmaku_speed\x18\x0f \x01(\x05\x12&\n\x1eplayer_danmaku_enableblocklist\x18\x10 '
    b'\x01(\x08\x12$\n\x1cinline_player_danmaku_switch\x18\x11 \x01('
    b'\x08\x12$\n\x1cinline_player_danmaku_config\x18\x12 \x01(\x05\x12&\n\x1eplayer_danmaku_ios_switch_save\x18\x13 '
    b'\x01(\x05\x12)\n!player_danmaku_senior_mode_switch\x18\x14 \x01('
    b'\x05\"K\n\x18\x44\x61nmuPlayerDynamicConfig\x12\x10\n\x08progress\x18\x01 \x01('
    b'\x05\x12\x1d\n\x15player_danmaku_domain\x18\x0e \x01('
    b'\x02\"\xce\x01\n\x15\x44\x61nmuPlayerViewConfig\x12@\n\x1d\x64\x61nmuku_default_player_config\x18\x01 \x01('
    b'\x0b\x32\x19.DanmuDefaultPlayerConfig\x12\x31\n\x15\x64\x61nmuku_player_config\x18\x02 \x01('
    b'\x0b\x32\x12.DanmuPlayerConfig\x12@\n\x1d\x64\x61nmuku_player_dynamic_config\x18\x03 \x03('
    b'\x0b\x32\x19.DanmuPlayerDynamicConfig\"\xab\x03\n\x14\x44\x61nmuWebPlayerConfig\x12\x11\n\tdm_switch\x18\x01 '
    b'\x01(\x08\x12\x11\n\tai_switch\x18\x02 \x01(\x08\x12\x10\n\x08\x61i_level\x18\x03 \x01('
    b'\x05\x12\x10\n\x08\x62locktop\x18\x04 \x01(\x08\x12\x13\n\x0b\x62lockscroll\x18\x05 \x01('
    b'\x08\x12\x13\n\x0b\x62lockbottom\x18\x06 \x01(\x08\x12\x12\n\nblockcolor\x18\x07 \x01('
    b'\x08\x12\x14\n\x0c\x62lockspecial\x18\x08 \x01(\x08\x12\x14\n\x0cpreventshade\x18\t \x01('
    b'\x08\x12\r\n\x05\x64mask\x18\n \x01(\x08\x12\x0f\n\x07opacity\x18\x0b \x01(\x02\x12\x0e\n\x06\x64marea\x18\x0c '
    b'\x01(\x05\x12\x11\n\tspeedplus\x18\r \x01(\x02\x12\x10\n\x08\x66ontsize\x18\x0e \x01('
    b'\x02\x12\x12\n\nscreensync\x18\x0f \x01(\x08\x12\x11\n\tspeedsync\x18\x10 \x01('
    b'\x08\x12\x12\n\nfontfamily\x18\x11 \x01(\t\x12\x0c\n\x04\x62old\x18\x12 \x01(\x08\x12\x12\n\nfontborder\x18\x13 '
    b'\x01(\x05\x12\x11\n\tdraw_type\x18\x14 \x01(\t\x12\x1a\n\x12senior_mode_switch\x18\x15 \x01('
    b'\x05\"A\n\x0f\x44mExpoReportReq\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x0b\n\x03oid\x18\x02 \x01('
    b'\x03\x12\r\n\x05spmid\x18\x04 \x01(\t\"\x11\n\x0f\x44mExpoReportRes\"\xab\x07\n\x11\x44mPlayerConfigReq\x12\n\n'
    b'\x02ts\x18\x01 \x01(\x03\x12$\n\x06switch\x18\x02 \x01('
    b'\x0b\x32\x14.PlayerDanmakuSwitch\x12-\n\x0bswitch_save\x18\x03 \x01('
    b'\x0b\x32\x18.PlayerDanmakuSwitchSave\x12:\n\x12use_default_config\x18\x04 \x01('
    b'\x0b\x32\x1e.PlayerDanmakuUseDefaultConfig\x12@\n\x15\x61i_recommended_switch\x18\x05 \x01('
    b'\x0b\x32!.PlayerDanmakuAiRecommendedSwitch\x12>\n\x14\x61i_recommended_level\x18\x06 \x01(\x0b\x32 '
    b'.PlayerDanmakuAiRecommendedLevel\x12(\n\x08\x62locktop\x18\x07 \x01('
    b'\x0b\x32\x16.PlayerDanmakuBlocktop\x12.\n\x0b\x62lockscroll\x18\x08 \x01('
    b'\x0b\x32\x19.PlayerDanmakuBlockscroll\x12.\n\x0b\x62lockbottom\x18\t \x01('
    b'\x0b\x32\x19.PlayerDanmakuBlockbottom\x12\x32\n\rblockcolorful\x18\n \x01('
    b'\x0b\x32\x1b.PlayerDanmakuBlockcolorful\x12.\n\x0b\x62lockrepeat\x18\x0b \x01('
    b'\x0b\x32\x19.PlayerDanmakuBlockrepeat\x12\x30\n\x0c\x62lockspecial\x18\x0c \x01('
    b'\x0b\x32\x1a.PlayerDanmakuBlockspecial\x12&\n\x07opacity\x18\r \x01('
    b'\x0b\x32\x15.PlayerDanmakuOpacity\x12\x32\n\rscalingfactor\x18\x0e \x01('
    b'\x0b\x32\x1b.PlayerDanmakuScalingfactor\x12$\n\x06\x64omain\x18\x0f \x01('
    b'\x0b\x32\x14.PlayerDanmakuDomain\x12\"\n\x05speed\x18\x10 \x01('
    b'\x0b\x32\x13.PlayerDanmakuSpeed\x12\x36\n\x0f\x65nableblocklist\x18\x11 \x01('
    b'\x0b\x32\x1d.PlayerDanmakuEnableblocklist\x12=\n\x19inlinePlayerDanmakuSwitch\x18\x12 \x01('
    b'\x0b\x32\x1a.InlinePlayerDanmakuSwitch\x12:\n\x12senior_mode_switch\x18\x13 \x01('
    b'\x0b\x32\x1e.PlayerDanmakuSeniorModeSwitch\"/\n\x0b\x44mSegConfig\x12\x11\n\tpage_size\x18\x01 \x01('
    b'\x03\x12\r\n\x05total\x18\x02 \x01(\x03\"_\n\x10\x44mSegMobileReply\x12\x1b\n\x05\x65lems\x18\x01 \x03('
    b'\x0b\x32\x0c.DanmakuElem\x12\r\n\x05state\x18\x02 \x01(\x05\x12\x1f\n\x07\x61i_flag\x18\x03 \x01('
    b'\x0b\x32\x0e.DanmakuAIFlag\"g\n\x0e\x44mSegMobileReq\x12\x0b\n\x03pid\x18\x01 \x01('
    b'\x03\x12\x0b\n\x03oid\x18\x02 \x01(\x03\x12\x0c\n\x04type\x18\x03 \x01(\x05\x12\x15\n\rsegment_index\x18\x04 '
    b'\x01(\x03\x12\x16\n\x0eteenagers_mode\x18\x05 \x01(\x05\"<\n\rDmSegOttReply\x12\x0e\n\x06\x63losed\x18\x01 '
    b'\x01(\x08\x12\x1b\n\x05\x65lems\x18\x02 \x03('
    b'\x0b\x32\x0c.DanmakuElem\"L\n\x0b\x44mSegOttReq\x12\x0b\n\x03pid\x18\x01 \x01(\x03\x12\x0b\n\x03oid\x18\x02 '
    b'\x01(\x03\x12\x0c\n\x04type\x18\x03 \x01(\x05\x12\x15\n\rsegment_index\x18\x04 \x01('
    b'\x03\"<\n\rDmSegSDKReply\x12\x0e\n\x06\x63losed\x18\x01 \x01(\x08\x12\x1b\n\x05\x65lems\x18\x02 \x03('
    b'\x0b\x32\x0c.DanmakuElem\"L\n\x0b\x44mSegSDKReq\x12\x0b\n\x03pid\x18\x01 \x01(\x03\x12\x0b\n\x03oid\x18\x02 '
    b'\x01(\x03\x12\x0c\n\x04type\x18\x03 \x01(\x05\x12\x15\n\rsegment_index\x18\x04 \x01('
    b'\x03\"\xdb\x03\n\x0b\x44mViewReply\x12\x0e\n\x06\x63losed\x18\x01 \x01(\x08\x12\x18\n\x04mask\x18\x02 \x01('
    b'\x0b\x32\n.VideoMask\x12 \n\x08subtitle\x18\x03 \x01('
    b'\x0b\x32\x0e.VideoSubtitle\x12\x13\n\x0bspecial_dms\x18\x04 \x03(\t\x12#\n\x07\x61i_flag\x18\x05 \x01('
    b'\x0b\x32\x12.DanmakuFlagConfig\x12-\n\rplayer_config\x18\x06 \x01('
    b'\x0b\x32\x16.DanmuPlayerViewConfig\x12\x16\n\x0esend_box_style\x18\x07 \x01(\x05\x12\r\n\x05\x61llow\x18\x08 '
    b'\x01(\x08\x12\x11\n\tcheck_box\x18\t \x01(\t\x12\x1a\n\x12\x63heck_box_show_msg\x18\n \x01('
    b'\t\x12\x18\n\x10text_placeholder\x18\x0b \x01(\t\x12\x19\n\x11input_placeholder\x18\x0c \x01('
    b'\t\x12\x1d\n\x15report_filter_content\x18\r \x03(\t\x12 \n\x0b\x65xpo_report\x18\x0e \x01('
    b'\x0b\x32\x0b.ExpoReport\x12(\n\x0f\x62uzzword_config\x18\x0f \x01('
    b'\x0b\x32\x0f.BuzzwordConfig\x12!\n\x0b\x65xpressions\x18\x10 \x03('
    b'\x0b\x32\x0c.Expressions\"X\n\tDmViewReq\x12\x0b\n\x03pid\x18\x01 \x01(\x03\x12\x0b\n\x03oid\x18\x02 \x01('
    b'\x03\x12\x0c\n\x04type\x18\x03 \x01(\x05\x12\r\n\x05spmid\x18\x04 \x01(\t\x12\x14\n\x0cis_hard_boot\x18\x05 '
    b'\x01(\x05\"\xc7\x02\n\x0e\x44mWebViewReply\x12\r\n\x05state\x18\x01 \x01(\x05\x12\x0c\n\x04text\x18\x02 \x01('
    b'\t\x12\x11\n\ttext_side\x18\x03 \x01(\t\x12\x1c\n\x06\x64m_sge\x18\x04 \x01(\x0b\x32\x0c.DmSegConfig\x12 '
    b'\n\x04\x66lag\x18\x05 \x01(\x0b\x32\x12.DanmakuFlagConfig\x12\x13\n\x0bspecial_dms\x18\x06 \x03('
    b'\t\x12\x11\n\tcheck_box\x18\x07 \x01(\x08\x12\r\n\x05\x63ount\x18\x08 \x01(\x03\x12\x1e\n\ncommandDms\x18\t '
    b'\x03(\x0b\x32\n.CommandDm\x12,\n\rplayer_config\x18\n \x01('
    b'\x0b\x32\x15.DanmuWebPlayerConfig\x12\x1d\n\x15report_filter_content\x18\x0b \x03('
    b'\t\x12!\n\x0b\x65xpressions\x18\x0c \x03('
    b'\x0b\x32\x0c.Expressions\"*\n\nExpoReport\x12\x1c\n\x14should_report_at_end\x18\x01 \x01('
    b'\x08\"C\n\nExpression\x12\x0f\n\x07keyword\x18\x01 \x03(\t\x12\x0b\n\x03url\x18\x02 \x01('
    b'\t\x12\x17\n\x06period\x18\x03 \x03(\x0b\x32\x07.Period\"(\n\x0b\x45xpressions\x12\x19\n\x04\x64\x61ta\x18\x01 '
    b'\x03(\x0b\x32\x0b.Expression\"$\n\x06Period\x12\r\n\x05start\x18\x01 \x01(\x03\x12\x0b\n\x03\x65nd\x18\x02 '
    b'\x01(\x03\"*\n\x19InlinePlayerDanmakuSwitch\x12\r\n\x05value\x18\x01 \x01('
    b'\x08\"0\n\x1fPlayerDanmakuAiRecommendedLevel\x12\r\n\x05value\x18\x01 \x01(\x08\"1\n '
    b'PlayerDanmakuAiRecommendedSwitch\x12\r\n\x05value\x18\x01 \x01('
    b'\x08\")\n\x18PlayerDanmakuBlockbottom\x12\r\n\x05value\x18\x01 \x01('
    b'\x08\"+\n\x1aPlayerDanmakuBlockcolorful\x12\r\n\x05value\x18\x01 \x01('
    b'\x08\")\n\x18PlayerDanmakuBlockrepeat\x12\r\n\x05value\x18\x01 \x01('
    b'\x08\")\n\x18PlayerDanmakuBlockscroll\x12\r\n\x05value\x18\x01 \x01('
    b'\x08\"*\n\x19PlayerDanmakuBlockspecial\x12\r\n\x05value\x18\x01 \x01('
    b'\x08\"&\n\x15PlayerDanmakuBlocktop\x12\r\n\x05value\x18\x01 \x01('
    b'\x08\"$\n\x13PlayerDanmakuDomain\x12\r\n\x05value\x18\x01 \x01('
    b'\x02\"-\n\x1cPlayerDanmakuEnableblocklist\x12\r\n\x05value\x18\x01 \x01('
    b'\x08\"%\n\x14PlayerDanmakuOpacity\x12\r\n\x05value\x18\x01 \x01('
    b'\x02\"+\n\x1aPlayerDanmakuScalingfactor\x12\r\n\x05value\x18\x01 \x01('
    b'\x02\".\n\x1dPlayerDanmakuSeniorModeSwitch\x12\r\n\x05value\x18\x01 \x01('
    b'\x05\"#\n\x12PlayerDanmakuSpeed\x12\r\n\x05value\x18\x01 \x01('
    b'\x05\"7\n\x13PlayerDanmakuSwitch\x12\r\n\x05value\x18\x01 \x01(\x08\x12\x11\n\tcanIgnore\x18\x02 \x01(\x08\"('
    b'\n\x17PlayerDanmakuSwitchSave\x12\r\n\x05value\x18\x01 \x01('
    b'\x08\".\n\x1dPlayerDanmakuUseDefaultConfig\x12\r\n\x05value\x18\x01 \x01('
    b'\x08\")\n\x08Response\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01('
    b'\t\"\x96\x01\n\x0cSubtitleItem\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0e\n\x06id_str\x18\x02 \x01('
    b'\t\x12\x0b\n\x03lan\x18\x03 \x01(\t\x12\x0f\n\x07lan_doc\x18\x04 \x01(\t\x12\x14\n\x0csubtitle_url\x18\x05 '
    b'\x01(\t\x12\x19\n\x06\x61uthor\x18\x06 \x01(\x0b\x32\t.UserInfo\x12\x1b\n\x04type\x18\x07 \x01('
    b'\x0e\x32\r.SubtitleType\"\\\n\x08UserInfo\x12\x0b\n\x03mid\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01('
    b'\t\x12\x0b\n\x03sex\x18\x03 \x01(\t\x12\x0c\n\x04\x66\x61\x63\x65\x18\x04 \x01(\t\x12\x0c\n\x04sign\x18\x05 '
    b'\x01(\t\x12\x0c\n\x04rank\x18\x06 \x01(\x05\"S\n\tVideoMask\x12\x0b\n\x03\x63id\x18\x01 \x01('
    b'\x03\x12\x0c\n\x04plat\x18\x02 \x01(\x05\x12\x0b\n\x03\x66ps\x18\x03 \x01(\x05\x12\x0c\n\x04time\x18\x04 \x01('
    b'\x03\x12\x10\n\x08mask_url\x18\x05 \x01(\t\"N\n\rVideoSubtitle\x12\x0b\n\x03lan\x18\x01 \x01('
    b'\t\x12\x0e\n\x06lanDoc\x18\x02 \x01(\t\x12 \n\tsubtitles\x18\x03 \x03('
    b'\x0b\x32\r.SubtitleItem*L\n\tDMAttrBit\x12\x14\n\x10\x44MAttrBitProtect\x10\x00\x12\x15\n\x11'
    b'\x44MAttrBitFromLive\x10\x01\x12\x12\n\x0e\x44MAttrHighLike\x10\x02*\x1e\n\x0cSubtitleType\x12\x06\n\x02\x43'
    b'\x43\x10\x00\x12\x06\n\x02\x41I\x10\x01\x32\x94\x02\n\x02\x44M\x12\x31\n\x0b\x44mSegMobile\x12\x0f'
    b'.DmSegMobileReq\x1a\x11.DmSegMobileReply\x12\"\n\x06\x44mView\x12\n.DmViewReq\x1a\x0c.DmViewReply\x12/\n\x0e'
    b'\x44mPlayerConfig\x12\x12.DmPlayerConfigReq\x1a\t.Response\x12('
    b'\n\x08\x44mSegOtt\x12\x0c.DmSegOttReq\x1a\x0e.DmSegOttReply\x12('
    b'\n\x08\x44mSegSDK\x12\x0c.DmSegSDKReq\x1a\x0e.DmSegSDKReply\x12\x32\n\x0c\x44mExpoReport\x12\x10'
    b'.DmExpoReportReq\x1a\x10.DmExpoReportResb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'my_pb2', globals())
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._options = None
    _DMATTRBIT._serialized_start = 6726
    _DMATTRBIT._serialized_end = 6802
    _SUBTITLETYPE._serialized_start = 6804
    _SUBTITLETYPE._serialized_end = 6834
    _BUZZWORDCONFIG._serialized_start = 12
    _BUZZWORDCONFIG._serialized_end = 67
    _BUZZWORDSHOWCONFIG._serialized_start = 69
    _BUZZWORDSHOWCONFIG._serialized_end = 189
    _COMMANDDM._serialized_start = 192
    _COMMANDDM._serialized_end = 353
    _DANMAKUAIFLAG._serialized_start = 355
    _DANMAKUAIFLAG._serialized_end = 402
    _DANMAKUELEM._serialized_start = 405
    _DANMAKUELEM._serialized_end = 619
    _DANMAKUFLAG._serialized_start = 621
    _DANMAKUFLAG._serialized_end = 662
    _DANMAKUFLAGCONFIG._serialized_start = 664
    _DANMAKUFLAGCONFIG._serialized_end = 739
    _DANMUDEFAULTPLAYERCONFIG._serialized_start = 742
    _DANMUDEFAULTPLAYERCONFIG._serialized_end = 1330
    _DANMUPLAYERCONFIG._serialized_start = 1333
    _DANMUPLAYERCONFIG._serialized_end = 2099
    _DANMUPLAYERDYNAMICCONFIG._serialized_start = 2101
    _DANMUPLAYERDYNAMICCONFIG._serialized_end = 2176
    _DANMUPLAYERVIEWCONFIG._serialized_start = 2179
    _DANMUPLAYERVIEWCONFIG._serialized_end = 2385
    _DANMUWEBPLAYERCONFIG._serialized_start = 2388
    _DANMUWEBPLAYERCONFIG._serialized_end = 2815
    _DMEXPOREPORTREQ._serialized_start = 2817
    _DMEXPOREPORTREQ._serialized_end = 2882
    _DMEXPOREPORTRES._serialized_start = 2884
    _DMEXPOREPORTRES._serialized_end = 2901
    _DMPLAYERCONFIGREQ._serialized_start = 2904
    _DMPLAYERCONFIGREQ._serialized_end = 3843
    _DMSEGCONFIG._serialized_start = 3845
    _DMSEGCONFIG._serialized_end = 3892
    _DMSEGMOBILEREPLY._serialized_start = 3894
    _DMSEGMOBILEREPLY._serialized_end = 3989
    _DMSEGMOBILEREQ._serialized_start = 3991
    _DMSEGMOBILEREQ._serialized_end = 4094
    _DMSEGOTTREPLY._serialized_start = 4096
    _DMSEGOTTREPLY._serialized_end = 4156
    _DMSEGOTTREQ._serialized_start = 4158
    _DMSEGOTTREQ._serialized_end = 4234
    _DMSEGSDKREPLY._serialized_start = 4236
    _DMSEGSDKREPLY._serialized_end = 4296
    _DMSEGSDKREQ._serialized_start = 4298
    _DMSEGSDKREQ._serialized_end = 4374
    _DMVIEWREPLY._serialized_start = 4377
    _DMVIEWREPLY._serialized_end = 4852
    _DMVIEWREQ._serialized_start = 4854
    _DMVIEWREQ._serialized_end = 4942
    _DMWEBVIEWREPLY._serialized_start = 4945
    _DMWEBVIEWREPLY._serialized_end = 5272
    _EXPOREPORT._serialized_start = 5274
    _EXPOREPORT._serialized_end = 5316
    _EXPRESSION._serialized_start = 5318
    _EXPRESSION._serialized_end = 5385
    _EXPRESSIONS._serialized_start = 5387
    _EXPRESSIONS._serialized_end = 5427
    _PERIOD._serialized_start = 5429
    _PERIOD._serialized_end = 5465
    _INLINEPLAYERDANMAKUSWITCH._serialized_start = 5467
    _INLINEPLAYERDANMAKUSWITCH._serialized_end = 5509
    _PLAYERDANMAKUAIRECOMMENDEDLEVEL._serialized_start = 5511
    _PLAYERDANMAKUAIRECOMMENDEDLEVEL._serialized_end = 5559
    _PLAYERDANMAKUAIRECOMMENDEDSWITCH._serialized_start = 5561
    _PLAYERDANMAKUAIRECOMMENDEDSWITCH._serialized_end = 5610
    _PLAYERDANMAKUBLOCKBOTTOM._serialized_start = 5612
    _PLAYERDANMAKUBLOCKBOTTOM._serialized_end = 5653
    _PLAYERDANMAKUBLOCKCOLORFUL._serialized_start = 5655
    _PLAYERDANMAKUBLOCKCOLORFUL._serialized_end = 5698
    _PLAYERDANMAKUBLOCKREPEAT._serialized_start = 5700
    _PLAYERDANMAKUBLOCKREPEAT._serialized_end = 5741
    _PLAYERDANMAKUBLOCKSCROLL._serialized_start = 5743
    _PLAYERDANMAKUBLOCKSCROLL._serialized_end = 5784
    _PLAYERDANMAKUBLOCKSPECIAL._serialized_start = 5786
    _PLAYERDANMAKUBLOCKSPECIAL._serialized_end = 5828
    google._serialized_start = 5830
    google._serialized_end = 5868
    _PLAYERDANMAKUDOMAIN._serialized_start = 5870
    _PLAYERDANMAKUDOMAIN._serialized_end = 5906
    _PLAYERDANMAKUENABLEBLOCKLIST._serialized_start = 5908
    _PLAYERDANMAKUENABLEBLOCKLIST._serialized_end = 5953
    _PLAYERDANMAKUOPACITY._serialized_start = 5955
    _PLAYERDANMAKUOPACITY._serialized_end = 5992
    _PLAYERDANMAKUSCALINGFACTOR._serialized_start = 5994
    _PLAYERDANMAKUSCALINGFACTOR._serialized_end = 6037
    _PLAYERDANMAKUSENIORMODESWITCH._serialized_start = 6039
    _PLAYERDANMAKUSENIORMODESWITCH._serialized_end = 6085
    _PLAYERDANMAKUSPEED._serialized_start = 6087
    _PLAYERDANMAKUSPEED._serialized_end = 6122
    _PLAYERDANMAKUSWITCH._serialized_start = 6124
    _PLAYERDANMAKUSWITCH._serialized_end = 6179
    _PLAYERDANMAKUSWITCHSAVE._serialized_start = 6181
    _PLAYERDANMAKUSWITCHSAVE._serialized_end = 6221
    _PLAYERDANMAKUUSEDEFAULTCONFIG._serialized_start = 6223
    _PLAYERDANMAKUUSEDEFAULTCONFIG._serialized_end = 6269
    _RESPONSE._serialized_start = 6271
    _RESPONSE._serialized_end = 6312
    _SUBTITLEITEM._serialized_start = 6315
    _SUBTITLEITEM._serialized_end = 6465
    _USERINFO._serialized_start = 6467
    _USERINFO._serialized_end = 6559
    _VIDEOMASK._serialized_start = 6561
    _VIDEOMASK._serialized_end = 6644
    _VIDEOSUBTITLE._serialized_start = 6646
    _VIDEOSUBTITLE._serialized_end = 6724
    _DM._serialized_start = 6837
    _DM._serialized_end = 7113
# @@protoc_insertion_point(module_scope)
